- platform: generic
  stream_source: !secret lorex-rtsp-frontporch
  still_image_url: !secret lorex-img-frontporch
  name: "Camera Front Porch"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-garage
  still_image_url: !secret lorex-img-garage
  name: "Camera Garage"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-frontyard
  still_image_url: !secret lorex-img-frontyard
  name: "Camera Front Yard"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-driveway
  still_image_url: !secret lorex-img-driveway
  name: "Camera Driveway"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-northbackyard
  still_image_url: !secret lorex-img-northbackyard
  name: "Camera North Backyard"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-southbackyard
  still_image_url: !secret lorex-img-southbackyard
  name: "Camera South Backyard"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-backdeck
  still_image_url: !secret lorex-img-backdeck
  name: "Camera Back Deck"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: generic
  stream_source: !secret lorex-rtsp-backdoor
  still_image_url: !secret lorex-img-backdoor
  name: "Camera Back Door"
  verify_ssl: false
  authentication: basic
  username: !secret lorex-dvr-user
  password: !secret lorex-dvr-password

- platform: mjpeg
  name: OctoPrint
  still_image_url: http://octopi.home.rowkar.net/webcam/?action=snapshot
  mjpeg_url: http://octopi.home.rowkar.net/webcam/?action=stream