# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: "Rowkar Home"
  latitude: 38.998860
  longitude: -94.681990
  unit_system: imperial
  temperature_unit: F
  time_zone: "America/Chicago"
  currency: USD
  elevation: 331
  external_url: "https://xcy5al4q2ajb4eguaahnhaoz9j53kiqt.ui.nabu.casa"
  internal_url: "http://10.10.10.125:8123"
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

#automation: !include automations.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/manual/

script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.10.220

camera: !include cameras.yaml

#sensor: !include sensors.yaml
sensor: !include_dir_merge_list sensors/

#influxdb: !include influxdb.yaml

envisalink: !include envisalink.yaml

cover: !include cover.yaml

panel_custom: !include panels.yaml
