- platform: template
  covers:
    north_garage_door:
      device_class: garage
      unique_id: "north_garage_door_cover"
      friendly_name: "North Garage Door"
      value_template: >-
        {% if is_state('binary_sensor.garage_door_north_is_open','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_north_door_control
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_north_door_control
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_north_door_control
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_north_is_open','on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}

    south_garage_door:
      device_class: garage
      friendly_name: "South Garage Door"
      unique_id: "south_garage_door_cover"
      value_template: >-
        {% if is_state('binary_sensor.garage_door_south_is_open','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_south_door_control
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_south_door_control
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_south_door_control
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_south_is_open','on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
