- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.pm1 }}"
  name: "enviro_pm1"
  unit_of_measurement: "pm"
  icon: "mdi:thought-bubble-outline"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.pm10 }}"
  name: "enviro_pm10"
  unit_of_measurement: "pm"
  icon: "mdi:thought-bubble-outline"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.pm25 }}"
  name: "enviro_pm2"
  unit_of_measurement: "pm"
  icon: "mdi:thought-bubble"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.humidity }}"
  name: "enviro_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.pressure }}"
  name: "enviro_pressure"
  unit_of_measurement: "Pa"
  icon: "mdi:arrow-down-bold"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.temperature }}"
  name: "enviro_temperature"
  unit_of_measurement: "C"
  icon: "mdi:thermometer"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.lux }}"
  name: "enviro_lux"
  unit_of_measurement: "lx"
  icon: "mdi:weather-sunny"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.nh3 }}"
  name: "enviro_nh3"
  unit_of_measurement: "nh3"
  icon: "mdi:thought-bubble"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.reduced }}"
  name: "enviro_reduced"
  unit_of_measurement: "CO"
  icon: "mdi:thought-bubble"

- platform: mqtt
  state_topic: "enviro"
  value_template: "{{ value_json.oxidised }}"
  name: "enviro_oxidised "
  unit_of_measurement: "no2"
  icon: "mdi:thought-bubble"