- platform: template
  sensors:
    unavailable_devices:
      friendly_name: Devices needing attention
      value_template: >
        {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | selectattr('domain','in', ['switch','light','sensor']) | list | length }}
      attribute_templates:
        entities: >
          {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | selectattr('domain','in', ['switch', 'light', 'sensor']) | map(attribute='entity_id') | list | join('\n') }}