esphome:
  name: "sump-batt-mon"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  id: wifi_id

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-15E9Ec"
    password: "hUBzMGAy25aJ"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      id: esp_ip_address
      internal: true

sensor:
  - platform: adc
    pin: A0
    name: "Sump Pump Monitor Raw Input"
    id: "sump_pump_monitor_raw_input"
    update_interval: 60s
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
  
  - platform: template
    name: "Sump Pump Monitor Battery Voltage"
    id: "sump_pump_monitor_battery_volt"
    update_interval: 60s
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    lambda: |-
      return id(sump_pump_monitor_raw_input).state;
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.57129 -> 10.00
          - 0.59570 -> 10.46
          - 0.62891 -> 11.03
          - 0.65430 -> 11.50
          - 0.69141 -> 12.07
          - 0.71500 -> 12.51
          - 0.74414 -> 13.01
          - 0.77148 -> 13.52
          - 0.80273 -> 14.05
          - 0.82715 -> 14.50
          - 0.85742 -> 15.02

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  frequency: 400kHz

font:
  - file: 'fonts/Google_Sans_Regular.ttf'
    id: my_font
    size: 10
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
      '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
      'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
      'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
      'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
      'u', 'v', 'w', 'x', 'y', 'z', '/', '\t']

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    #reset_pin: D0
    address: 0x3C
    update_interval: 1s
    lambda: |-
      it.printf( 0, 0, id(my_font), "Wifi:");
      if (id(wifi_id).is_connected()){
        it.printf( 2, 12, id(my_font), "%s", id(esp_ip_address).state.c_str());
      } else {
        it.printf( 2, 12, id(my_font), "%s", "Disconnected");
      }

      it.printf( 0, 24, id(my_font), "Batt: %.2fV", id(sump_pump_monitor_battery_volt).state );
      it.printf( 0, 36, id(my_font), "Raw:  %.2fV", id(sump_pump_monitor_raw_input).state );